# Generated by Django 5.1.3 on 2025-04-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletin',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='boletin',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='boletin',
            name='contenido',
            field=models.TextField(),
        ),
    ]
