# Generated by Django 5.1.3 on 2025-05-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_boletin_fecha_modificacion_boletin_publicado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletin',
            name='es_plantilla',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boletin',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='boletines/'),
        ),
    ]
