# Generated by Django 5.1.3 on 2025-05-21 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0004_plantilla'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupabaseUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('user_class', models.CharField(db_column='class', max_length=255)),
                ('email', models.CharField(db_column='email', max_length=255, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
