# Generated by Django 5.1.3 on 2025-05-20 20:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_pdfs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentopdf',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
